settings:
  disable-plugins-command: false
  check-updates-boot: true
  check-updates-login: false
  download-updates-boot: false
  download-updates-login: false
  install-updates-boot: false
  install-updates-login: false

disabled-commands:
  - "plugin:command"